- hosts: nodes
  become: true

  tasks:
  
  - name: Remove Docker packages
    apt:
      name: "{{ item }}"
      state: absent
    loop:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc

  - name: Remove unused dependencies
    apt:
      autoremove: yes
      cache_valid_time: 0  # Force update

  - name: Update package lists
    apt:
      update_cache: yes

  - name: Install ca-certificates and curl
    apt:
      name:
        - ca-certificates
        - curl
      state: present



  - name: Create directory for Docker GPG key
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: 0755

  - name: Add Docker GPG apt Key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc


  - name: Set permissions for Docker GPG key
    shell: sudo chmod a+r /etc/apt/keyrings/docker.asc


  # - name: Add Docker GPG apt Key
  #   apt_key:
  #     url: https://download.docker.com/linux/ubuntu/gpg
  #     state: present

  # - name: Set permissions for Docker GPG key
  #   file:
  #     path: /etc/apt/keyrings/docker.asc
  #     mode: 0444


  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present


  - name: Update package lists (again, after adding repository)
    apt:
      update_cache: yes


  - name: Install containerd.io
    apt:
      name:
        - containerd.io
      state: present
 
  - name: Copy containerd config using shell
    shell: containerd config default > /etc/containerd/config.toml

  - name: To use the systemd cgroup driver in containerd with runc
    shell: sed -E -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

  - name: Systemctl Restart Containerd
    shell: systemctl restart containerd