- name: Add KUBECONFIG to master
  hosts: server1
  become: yes
  tasks:


  - name: Get Token join
    shell: kubeadm token create --print-join-command
    register: kubeadm_output

  
  - name: Show kubeadm init output
    debug:
      msg: "{{ kubeadm_output.stdout }}"


- name: Join nodes
  hosts: nodes
  become: yes

  tasks:
  - name: kubeadm reset
    shell: kubeadm reset --force

  - name: Show kubeadm init output
    debug:
      msg: "{{ hostvars['server1']['kubeadm_output']['stdout'] }}"

  - name: Join worker nodes to the cluster
    shell: "{{ hostvars['server1']['kubeadm_output']['stdout'] }}"
    when: "'kubeadm join' in hostvars['server1']['kubeadm_output']['stdout']"