- name: Retrieve versions of kubelet, kubectl, kubeadm, Docker, and containerd
  hosts: all
  tasks:
  - name: Get kubelet version
    shell:  kubelet --version
    register: kubelet_version
    ignore_errors: yes

  - name: Get kubectl version
    shell: kubectl version
    register: kubectl_version
    ignore_errors: yes

  - name: Get kubeadm version
    shell: kubeadm version
    register: kubeadm_version
    ignore_errors: yes

  - name: Get Docker version
    shell: docker version
    register: docker_version
    ignore_errors: yes

  - name: Get containerd version (using CLI)
    shell: containerd --version
    register: containerd_version
    when: >
      command.stdout.find("version:") != -1
    ignore_errors: yes

  - name: Get containerd version (using systemd)
    shell: systemctl status containerd | grep Version
    register: containerd_version
    when: >
      command.stdout.find("version:") == -1
    ignore_errors: yes

  - name: Print versions
    debug:
      msg:
        - "kubelet: {{ kubelet_version.stdout }}"
        - "kubectl: {{ kubectl_version.stdout }}"
        - "kubeadm: {{ kubeadm_version.stdout }}"
        - "Docker: {{ docker_version.stdout }}"
        - "containerd: {{ containerd_version.stdout }}"
